services:
  mongodb:
    image: mongo:7.0
    container_name: south-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: southdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: south-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  app:
    build: .
    container_name: south-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongodb:27017/southdb?authSource=admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    restart: on-failure

volumes:
  mongodb_data:
  rabbitmq_data: